### ISSUE TITLE
How to install fpp by local file.

### ISSUE THREAD

**Issue by Zanejins** [fprime-community/fpp#245]
I can't access github on my ubuntu due to network problems. 
But I have downloaded native-fpp-linux-x86_64 and fprime-fpp-1.0.2.

When I run python setup.py in the fprime-fpp-1.0.2 directory,  it still be from github, how do I change it to native-fpp-linux-x86_64 which I have downloaded locally. Thank you.
![image](https://user-images.githubusercontent.com/98217021/230534976-8bb150ec-7580-492c-a92f-2ecf1248e95a.png)

**Comment by ThibFrgsGmz** [comment]
If I remember well, you can hack the installation but changing the various path in `fprime_fpp_install.py`.
https://github.com/fprime-community/fpp/blob/f8290b9f9c22f663b8922df8845da7f739941cb8/fprime_fpp/fprime_fpp_install.py#L78
I did it once a few months ago because like you I had no internet connection.

**Comment by ThibFrgsGmz** [comment]
According to https://github.com/nasa/fprime/discussions/1958#discussioncomment-5551030 this issue can be closed, right?

**Comment by bocchino** [comment]
Yes, thanks!
