### ISSUE TITLE
Resolution of File Locations Does Not Respect Symbolic Links

### ISSUE THREAD

**Issue by LeStarch** [fprime-community/fpp#370]
https://github.com/fprime-community/fpp/blob/63799b4b1fbe57db87f9445d7a31fc5ff1c2d2da/compiler/lib/src/main/scala/codegen/CppWriter/CppWriterState.scala#L45

> See discussion below

By calling `.normalize` after `.toAbsolutePath` causes links to resolve into a "real path".  When F´  is building within a symlinked directory this causes incorrect include paths to be generated because `removeLongestPathPrefix` does not deal in realpaths and thus does not strip off the prefix when it should.

It is recommended that `.normalize` be removed in the above call, and all uses of `.normalize` should be reviewed.

**Comment by LeStarch** [comment]
This is not the issue, it seems to be dependent on the working directory.

**Comment by LeStarch** [comment]
The issue comes from the use of working directory to generate path names.

```
java.nio.file.Paths.get(fileName)
```

When filename does not contain a path (just a name) then Java prepends the working directory name.  However, the JVM resolves symlinks at startup when determining the working directory name.  Thus paths generated with the above will **always** resolve paths and thus fail on symlinks.

The only way to fix this would be to pass in the working directory as an argument to the process and use that instead of Java's understanding of the working directory.

> Since Scala is dependent on the JVM it is limited by the same flaws.  Theoretically python has the same issue.

**Comment by bocchino** [comment]
Can't we just do everything in the real directory, i.e., have the build system pass in the real directory prefixes to -p?

**Comment by bocchino** [comment]
If it works, this seems like a more robust solution than trying to figure out which of any number of path aliases to use when resolving path names.

**Comment by bocchino** [comment]
This issue seems to be requesting a change to the spec. In particular, the FPP spec assumes that each file has a unique location, expressed as a path in the file system. Sym links are arbitrary path aliases, so they cannot function as FPP locations. I suspect this issue can be solved by working in the domain of true filesystem paths. If not, let's discuss.

**Comment by bocchino** [comment]
I looked at the underlying issue nasa/fprime#1604. I think the issue is that when we run `fpp-to-xml foo/bar.fpp`, and `foo` is a symlink to `baz`, the location of the input file becomes `baz/bar.fpp` instead of `foo/bar.fpp`.

To check this, you could look at the locs.fpp file for the example shown in the issue.

If this is correct, then I see two ways to fix it: (1) get the FPP locations to respect the symlinks or (2) provide the -p input with regard to the real path names. I'm not sure how hard (1) would be. I'm on vacation and away from my FPP installation right now.

**Comment by bocchino** [comment]
> The issue comes from the use of working directory to generate path names.

I don't think that is causing the behavior described in nasa/fprime#1604. When a symbol is imported, the import path is generated by using the location of the symbol. I don't think the working directory comes into play here.

**Comment by bocchino** [comment]
So it could have to do with the working directory, but for a different reason. When the file name string comes in on the command line, it gets converted to an FPP file here:

https://github.com/fprime-community/fpp/blob/63799b4b1fbe57db87f9445d7a31fc5ff1c2d2da/compiler/lib/src/main/scala/util/File.scala#L61

If the file names being passed in on the command line are relative to the working directory, then the working directory would be an issue.

**Comment by LeStarch** [comment]
After thinking on this more, I believe the correct fix is to have CMake, which calls into FPP, respect the resolved paths that the JVM deals in.  Thus I will add an issue over there!

**Comment by LeStarch** [comment]
Closing in favor of: https://github.com/nasa/fprime/issues/2455

**Comment by bocchino** [comment]
Sounds good! I opened an issue to document this idiosyncrasy in the User's Guide. See #371.
